---
- name: install docker requirements
  hosts: all
  tasks:

    - apt_key: keyserver=hkp://pgp.mit.edu:80 id=58118E89F3A912897C070ADBF76221572C52609D
      become: true

    - apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
      become: true

    - name: install apt packages
      apt: "name='{{ item }}' state=present"
      become: true
      with_items:
        - docker-engine

    - name: install via pip
      pip:
        name: "{{item}}"
      become: true
      with_items:
      - docker-py
      - docker-compose
      - pyyaml
