- name: docker services
  hosts: all
  become: yes

  tasks:

  - docker_service:
      project_name: dokuwiki
      definition:
       version: '2'
       services:
        dokuwiki:
          image: mprasil/dokuwiki
          container_name: dokuwiki
          volumes:
            - "{{ dokuwiki_data_path }}/data:/dokuwiki/data"
            - "{{ dokuwiki_data_path }}/conf:/dokuwiki/conf"
            - "{{ dokuwiki_data_path }}/lib/plugins:/dokuwiki/lib/plugins"
          ports:
            - "{{ services['dokuwiki']['internal_port'] }}:80"

  - docker_service:
      project_name: tt-rss
      definition:
         version: '2'
         services:
          ttrss:
            image: clue/ttrss
            links:
            - "ttrss-postgres:db"
            ports:
            - "{{ services['ttrss']['internal_port'] }}:80"
            container_name: ttrss
            environment:
            - "DB_PORT=5432"
            - "DB_TYPE=pgsql"
            - "DB_HOST=ttrss-postgres"
            - "SELF_URL_PATH=https://{{ services['ttrss']['domain'] }}/"

          ttrss-postgres:
            image: nornagon/postgres
            container_name: tinydatabase